# main text of home
name: Dênis Araújo da Silva
bio: Computer Engineer with a Master's in Digital Management

# twitter summary info
description: A blog about technology and my thoughts

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://www.canva.com/design/DAF16kHfBEs/5KeS06qhRCzgegiALsWZBw/view?utm_content=DAF16kHfBEs&utm_campaign=designshare&utm_medium=link&utm_source=editor

url: http://silvadenisaraujo.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: "G-F3ZMBPPS91"

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
    shortname:
    categories:

# if you don't have any of social below, comment the line
linkedin: silvadenisaraujo
github: silvadenisaraujo

authors:
    silvadenis:
        name: Dênis Araújo da Silva
        bio: Computer Engineer with a Master's in Digital Management
        external-image: false
        picture: assets/images/profile.jpg

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
    - jekyll-seo-tag
    - jekyll-gist
    - jekyll-feed
    - jemoji
    - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
            - development
            - stage

exclude:
    ["travis.sh", "Rakefile", "README.md", "Gemfile", "Gemfile.lock", "FAQ.md"]
